title: Bryan Jacobs
logo: /assets/img/IMG_6868-photoaidcom-cropped.jpeg
description: >
  Data Scientist with an M.S. in Data Science from the University of Arizonaâ€™s College of Information Science. Experienced in machine learning, statistical programming, data visualization, and bioinformatics, supported by a strong analytical foundation from a B.A. in Mathematics from SUNY Geneseo.
  <br><br>
  Currently seeking full-time roles in Data Science, Machine Learning, Bioinformatics, and related fields.
  <br><br>
  <a href="https://www.linkedin.com/in/bryanjacobs822/">View My LinkedIn Profile</a>
email: bryanj82202@gmail.com
theme: jekyll-theme-minimal
